variable "aws_region" {
  description = "AWS region in which the FortiGate environment is deployed."
  type        = string
  default     = "us-east-1"
}

variable "region_code" {
  description = "Short region identifier used by the shared AWS naming modules."
  type        = string
  default     = "use1"

  validation {
    condition     = can(regex("^[a-z0-9-]{2,8}$", var.region_code))
    error_message = "region_code must contain 2-8 lowercase letters, numbers, or hyphens."
  }
}

variable "environment" {
  description = "Deployment environment."
  type        = string
  default     = "dev"

  validation {
    condition     = contains(["dev", "prod"], lower(var.environment))
    error_message = "environment must be dev or prod."
  }
}

variable "workload" {
  description = "Workload identifier used in resource names and tags."
  type        = string
  default     = "vfirewall"
}

variable "name_prefix" {
  description = "Prefix applied to resources created by this root composition."
  type        = string
  default     = "fgt-vfirewall"
}

variable "vpc_cidr" {
  description = "CIDR block for the AWS VPC."
  type        = string
  default     = "10.32.0.0/16"
}

variable "availability_zones" {
  description = "At least two AZs; simple mode uses the first and HA mode uses both."
  type        = list(string)
  default     = ["us-east-1a", "us-east-1b"]

  validation {
    condition     = length(var.availability_zones) >= 2
    error_message = "availability_zones must contain at least two availability zones."
  }
}

variable "nat_gateway_mode" {
  description = "NAT gateway topology for private firewall subnets."
  type        = string
  default     = "single"

  validation {
    condition     = contains(["none", "single", "per_az"], var.nat_gateway_mode)
    error_message = "nat_gateway_mode must be none, single, or per_az."
  }
}

variable "fortigate_deployment_mode" {
  description = "FortiGate topology: one node in simple mode or two nodes in HA mode."
  type        = string
  default     = "single"

  validation {
    condition     = contains(["single", "ha"], lower(var.fortigate_deployment_mode))
    error_message = "fortigate_deployment_mode must be single or ha."
  }
}

variable "fortigate_ami_id" {
  description = "FortiGate VM AMI ID for the selected AWS region. The default is a syntactic placeholder."
  type        = string
  default     = "ami-00000000000000000"

  validation {
    condition     = can(regex("^ami-[0-9a-fA-F]{8,17}$", var.fortigate_ami_id))
    error_message = "fortigate_ami_id must be an AWS AMI ID such as ami-0123456789abcdef0."
  }
}

variable "fortigate_license_type" {
  description = "FortiGate licensing model. Marketplace agreement and entitlement are not automated yet."
  type        = string
  default     = "byol"

  validation {
    condition     = contains(["byol", "payg"], lower(var.fortigate_license_type))
    error_message = "fortigate_license_type must be byol or payg."
  }
}

variable "fortigate_instance_type" {
  description = "EC2 instance type for each FortiGate node. Confirm FortiOS support and ENI limits."
  type        = string
  default     = "m5.large"
}

variable "fortigate_key_name" {
  description = "Optional EC2 key pair name for emergency console access."
  type        = string
  default     = null
}

variable "fortigate_user_data" {
  description = "Optional FortiOS bootstrap/user-data content. The AWS FortiGate bootstrap format is not generated by this composition."
  type        = string
  default     = null
  sensitive   = true
}

variable "fortigate_subnet_cidrs" {
  description = "Per-role, per-node subnet CIDRs. Simple mode needs a entries; HA mode needs a and b entries."
  type = object({
    external   = map(string)
    internal   = map(string)
    ha         = map(string)
    management = map(string)
  })
  default = {
    external   = { a = "10.32.192.0/25", b = "10.32.192.128/25" }
    internal   = { a = "10.32.193.0/25", b = "10.32.193.128/25" }
    ha         = { a = "10.32.194.0/28", b = "10.32.194.16/28" }
    management = { a = "10.32.195.0/24", b = "10.32.196.0/24" }
  }
}

variable "fortigate_private_ips" {
  description = "Optional static private IP for each interface and node. Leave an entry absent for AWS allocation."
  type = object({
    external   = map(string)
    internal   = map(string)
    ha         = map(string)
    management = map(string)
  })
  default = {
    external   = { a = "10.32.192.10", b = "10.32.192.138" }
    internal   = { a = "10.32.193.10", b = "10.32.193.138" }
    ha         = { a = "10.32.194.10", b = "10.32.194.26" }
    management = { a = "10.32.195.10", b = "10.32.196.10" }
  }
}

variable "management_cidr_blocks" {
  description = "CIDRs permitted to reach the FortiGate management services. Empty means no management ingress rule."
  type        = list(string)
  default     = []
}

variable "workload_cidr_blocks" {
  description = "CIDRs permitted to forward through the FortiGate data interfaces."
  type        = list(string)
  default     = []
}

variable "external_ingress_cidr_blocks" {
  description = "Explicit CIDRs permitted on the external interface when external ingress is enabled."
  type        = list(string)
  default     = []
}

variable "enable_external_ingress" {
  description = "Enable the explicitly supplied external ingress rules."
  type        = bool
  default     = false
}

variable "fortigate_iam_policy_json" {
  description = "Optional replacement IAM policy JSON for FortiGate failover/route automation. The default is a documented placeholder policy."
  type        = string
  default     = null
  sensitive   = true
}

variable "fortigate_root_volume_size" {
  description = "Root EBS volume size in GiB."
  type        = number
  default     = 20
}

variable "fortigate_kms_key_id" {
  description = "Optional KMS key ID/ARN for the encrypted FortiGate root volume."
  type        = string
  default     = null
}

variable "fortigate_monitoring" {
  description = "Enable detailed EC2 monitoring."
  type        = bool
  default     = true
}

variable "fortigate_disable_api_termination" {
  description = "Protect FortiGate instances from API termination."
  type        = bool
  default     = true
}

variable "fortigate_ebs_optimized" {
  description = "Enable EBS optimization on FortiGate instances."
  type        = bool
  default     = true
}

variable "enable_workload_routes" {
  description = "Create optional static routes in externally supplied workload route tables. HA route failover remains a placeholder."
  type        = bool
  default     = false
}

variable "workload_route_table_ids" {
  description = "Route table IDs that should send the destination CIDR to a FortiGate ENI."
  type        = set(string)
  default     = []
}

variable "route_next_hop_network_interface_id" {
  description = "FortiGate ENI ID used as the static route target. This is manual in HA until route automation exists."
  type        = string
  default     = null
}

variable "route_destination_cidr_block" {
  description = "Destination CIDR for optional workload routes."
  type        = string
  default     = "0.0.0.0/0"
}

variable "enable_internal_load_balancer" {
  description = "Placeholder switch for a future FortiGate-compatible AWS NLB/GWLB implementation."
  type        = bool
  default     = false
}

variable "internal_load_balancer_arn" {
  description = "Optional pre-existing load balancer ARN. No AWS-template module currently consumes it."
  type        = string
  default     = null
}

variable "tags" {
  description = "Additional tags applied to AWS resources."
  type        = map(string)
  default     = {}
}
